### ISSUE TITLE
Create pseudo worker from blob

### ISSUE THREAD

**Issue by nirdil** [nolanlawson/pseudo-worker#18]
Web Workers can be initialized from blobs like so:

    var worker = new Worker(URL.createObjectURL(blob));

Would be great if the PseudoWorker would be initializable using the same method.

**Comment by nolanlawson** [comment]
I don't see why pseudo-worker wouldn't work with blob URLs or data URLs. I just ran a quick test (https://github.com/nolanlawson/pseudo-worker/commit/08256cf0238f268dfc9e24c377d651662d15702e), and it works in Chrome at least. For other browsers, you may have to find other options because of CORS/security issues or bugs around how they handle blob URLs.
