### ISSUE TITLE
importScripts

### ISSUE THREAD

**Issue by Leooo** [nolanlawson/pseudo-worker#5]
Hello, when tyring to use importScripts (or self.importScripts) inside the window.pseudoWorker it is undefined:
`Uncaught ReferenceError: importScripts is not defined`

Thanks

**Comment by nolanlawson** [comment]
Unfortunately `importScripts` is not possible to polyfill in pseudo-worker, unless we did a synchronous blocking ajax call, which would make your UI freeze and not be a good user experience. 😕 

My recommendation in these cases is to use a tool like browserify/webpack/rollup to bundle a single `worker.js` file together, and avoid `importScripts` entirely. (I.e. you use `require()`/`import` instead of `importScripts()`. Even inside your worker, the performance will be better because you won't be making many separate network calls. Hope that helps!

**Comment by Leooo** [comment]
well that actually makes a lot of sense, as long as I don't have to reuse a script between workers. Thanks!

**Comment by nolanlawson** [comment]
if you do need to reuse scripts between workers, the performance hit is probably still not a big deal. Anyway, bundles will slow load faster than a script that needs to make separate network requests! :)

**Comment by JustinDrake** [comment]
FWIW, I'm using `pseudo-worker` for debugging purposes and having an `importScripts` (even blocking) would be helpful 👍
